custom_ekf_node:
  ros__parameters:
    odom_topic: /odom
    imu_topic: /imu
    output_topic: /odometry/filtered
    publish_tf: true
    odom_frame: odom
    base_frame: base_footprint
    use_imu_yaw: false
    process_noise_x: 0.05
    process_noise_y: 0.05
    process_noise_yaw: 0.03
    process_noise_vx: 0.10
    process_noise_vy: 0.10
    process_noise_wz: 0.08
    odom_pose_noise_x: 0.02
    odom_pose_noise_y: 0.02
    odom_pose_noise_yaw: 0.05
    odom_twist_noise_vx: 0.05
    odom_twist_noise_vy: 0.05
    odom_twist_noise_wz: 0.10
    imu_noise_yaw: 0.10
    imu_noise_wz: 0.02
